### ISSUE TITLE
Fix to "WARNING in vendors.bundle.js is 18.8 MB, and won't be precached." ?

### ISSUE THREAD

**Issue by raimon-segura** [yandeu/phaser-project-template#5]
Hi!,

After "npm start" it says:
> WARNING in vendors.bundle.js is 18.8 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.

Adding "maximumFileSizeToCacheInBytes: 20*1024*1024," at "InjectManifest" section, in webpack/webpack.common.js solves the issue.. its right?

```
new InjectManifest({
      swSrc: path.resolve(__dirname, '../pwa/sw.js'),
      maximumFileSizeToCacheInBytes: 20*1024*1024,
    })
```

Thanks!

**Comment by yandeu** [comment]
No, this is normal. `npm start` it optimized for developing and debugging.

Once your happy with your game, run `npm run build`, which will optimize the code for production. Then go into the /dist folder and serve your game using something like [live-server](https://www.npmjs.com/package/live-server) or [serve](https://www.npmjs.com/package/serve).

You should see that the bundle size is much smaller after running `npm run build`.

**Comment by yandeu** [comment]
Did it work? Have you seen the bundle size decreasing?

**Comment by raimon-segura** [comment]
Yes!, you are right 1.4MB with npm run build, 269KB with gzip :D

I'll ignore that warning at dev time.


Thanks for your quick response!
