### ISSUE TITLE
Reloaded version is always one behind

### ISSUE THREAD

**Issue by davidystephenson** [yandeu/phaser-project-template#6]
When running `npm start`, the watcher does notice changes and reloads the client. However, changes are not immediately seen in the browser. The browser version is always 1 iteration behind. If the browser is manually reloaded, the latest version is seen.

How can I make the HMR show the latest version?

**Comment by yandeu** [comment]
Have you activated the Service Worker? Try to disable/unsubscribe it during development.

**Comment by davidystephenson** [comment]
Thanks, the problem was not actually your service worker, but an orphan from another project that used the same local port. Unregistering it in the Application tab of my developer tools solved the problem. I was confused because I never activated yours. Thanks again for your help.
