### ISSUE TITLE
Change prettier config

### ISSUE THREAD

**Issue by MNewbigging** [yandeu/phaser-project-template#8]
Hi, this is more of a question than an issue - the .prettierrc file contains "@yandeu/prettier-config" - I'd like to change the config to include semi-colons at the end of lines, how can I do that?

**Comment by MNewbigging** [comment]
Derp, I just deleted that line and it does what I want, I'll add my own config there as necessary!

**Comment by yandeu** [comment]
You could also extend the `@yandeu/prettier-config`.

See https://github.com/yandeu/prettier-config#configuration

**Comment by MNewbigging** [comment]
Thanks!
